version: "3.7"

services: 
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: mern-server
    container_name: nodejs-express-server
    volumes: 
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on: 
      - mongo
    env_file: ./server/.env
    environment: 
      - NODE_ENV=development
    networks: 
      - mern-network
  mongo:
    image: mongo
    volumes: 
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks: 
      - mern-network
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: mern-client
    container_name: react-client
    volumes: 
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on: 
      - server
    ports: 
      - "3000:3000"
    networks: 
      - mern-network
    
networks: 
  mern-network:
    driver: bridge

volumes: 
  data-volume:
  node_modules:
  web-root:
    driver: local
